services:
  repready:
    image: repready:dev
    build:
      context: .
      dockerfile: RepReady/Dockerfile
    ports:
      - "5100:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    develop:
      watch:
        - action: rebuild
          path: ./RepReady
          ignore:
            - obj/
            - bin/
        - action: rebuild
          path: ./RepReady/Dockerfile
